<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;
use App\Models\ClientBranch;
use App\Models\ClientContact;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TenClientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::where('role', 'admin')->first();
        $adminId = $adminUser ? $adminUser->id : 1;

        $clientsData = [
            // ==========================================
            // GROUP A: Standard Statutory & Markup Model (Clients 1 to 5)
            // ==========================================
            [
                'company_name' => 'TechVanguard Solutions Pvt Ltd',
                'display_name_override' => 'TechVanguard',
                'client_code' => 'TVG-001',
                'industry' => 'Information Technology & Software',
                'contract_type' => 'agency',
                'contract_start_date' => '2025-01-01',
                'contract_end_date' => '2027-12-31',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAACT1234F',
                'tax_id' => 'TAX-TVG-001',
                'tan_number' => 'CHET12345F',
                'gstin' => '33AAACT1234F1Z5',
                'trust_registration_number' => 'TRST-TVG-001',
                'registration_number' => 'REG-TVG-2025',
                'cin_number' => 'U72200TN2025PTC123456',
                'incorporation_date' => '2020-04-15',
                'website' => 'https://techvanguard.example.com',
                'logo_path' => null,
                'accent_color' => '#1F3864',
                'payslip_template' => 'standard_blue',
                'registered_address_line_1' => 'Plot No. 12, Tidel Park',
                'registered_address_line_2' => 'Rajiv Gandhi Salai, Taramani',
                'registered_city' => 'Chennai',
                'registered_state' => 'Tamil Nadu',
                'registered_pin' => '600113',
                'primary_poc_name' => 'Ragul V',
                'primary_poc_email' => 'ragultn32vpm@gmail.com',
                'primary_poc_phone' => '9876543210',
                'billing_model' => 'markup',
                'markup_percentage' => 10.00,
                'fixed_fee_amount' => 0.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sat,sun',
                'default_notice_period_days' => 60,
                'status' => 'active',
                'ot_billing_rule' => 'double_rate',
                'payment_net_terms' => 30,
                'credit_limit' => 500000.00,
                'late_payment_penalty_pct' => 1.50,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-TVG-2026-001',
                'po_validity_date' => '2027-03-31',
                'po_value' => 5000000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 60,
                'pt_state' => 'Tamil Nadu',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'ceiling',
                'employer_pf_wage_basis' => 'ceiling',
                'pf_applicable' => true,
                'edli_exempted' => false,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'half_yearly',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'ctc_included',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 8.33,
                'clra_license_number' => 'CLRA-TN-2025-001',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'TN/CHE/0012345/000',
                'esi_code_number' => '31000123450000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'ragultn32vpm@gmail.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'premium',
                'cutoff_day' => 25,
                'payroll_lock_day' => 28,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 7,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Primary Tier-1 IT Client Partner.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                // Branch Details
                'branches' => [
                    [
                        'branch_name' => 'Chennai HQ',
                        'branch_code' => 'TVG-HQ',
                        'location' => 'Chennai',
                        'address_line_1' => 'Plot No. 12, Tidel Park',
                        'city' => 'Chennai',
                        'state' => 'Tamil Nadu',
                        'pin_code' => '600113',
                        'pt_registration_number' => 'PT-TN-600113-01',
                        'lwf_registration_number' => 'LWF-TN-600113-01',
                        'gstin' => '33AAACT1234F1Z5',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Ragul V',
                        'finance_poc_email' => 'ragultn32vpm@gmail.com',
                        'finance_poc_phone' => '9876543210',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'Apex Logistics & Freight LLP',
                'display_name_override' => 'Apex Logistics',
                'client_code' => 'APX-002',
                'industry' => 'Logistics & Supply Chain',
                'contract_type' => 'eor',
                'contract_start_date' => '2025-02-01',
                'contract_end_date' => '2028-01-31',
                'company_type' => 'llp',
                'country' => 'India',
                'pan_number' => 'AAAPA5678G',
                'tax_id' => 'TAX-APX-002',
                'tan_number' => 'CHEA56789G',
                'gstin' => '33AAAPA5678G1Z2',
                'trust_registration_number' => null,
                'registration_number' => 'LLP-APX-2025',
                'cin_number' => 'AAA-5678',
                'incorporation_date' => '2019-08-20',
                'website' => 'https://apexlogistics.example.com',
                'logo_path' => null,
                'accent_color' => '#0284C7',
                'payslip_template' => 'modern_navy',
                'registered_address_line_1' => 'Logistics Hub, NH-44',
                'registered_address_line_2' => 'Sriperumbudur Industrial Corridor',
                'registered_city' => 'Kanchipuram',
                'registered_state' => 'Tamil Nadu',
                'registered_pin' => '602105',
                'primary_poc_name' => 'Ram Kumar',
                'primary_poc_email' => 'ramkumar094677@gmail.com',
                'primary_poc_phone' => '9876543211',
                'billing_model' => 'markup',
                'markup_percentage' => 8.50,
                'fixed_fee_amount' => 0.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sun',
                'default_notice_period_days' => 30,
                'status' => 'active',
                'ot_billing_rule' => 'double_rate',
                'payment_net_terms' => 30,
                'credit_limit' => 300000.00,
                'late_payment_penalty_pct' => 1.50,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-APX-2026-002',
                'po_validity_date' => '2027-03-31',
                'po_value' => 3000000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 30,
                'pt_state' => 'Tamil Nadu',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'ceiling',
                'employer_pf_wage_basis' => 'ceiling',
                'pf_applicable' => true,
                'edli_exempted' => false,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'annual',
                'lwf_applicable' => false,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'ctc_included',
                'gratuity_applicable' => false,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 8.33,
                'clra_license_number' => 'CLRA-TN-2025-002',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'TN/CHE/0056789/000',
                'esi_code_number' => '31000567890000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'ramkumar094677@gmail.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'standard',
                'cutoff_day' => 24,
                'payroll_lock_day' => 27,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 7,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Major freight and warehouse operations partner.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Sriperumbudur Warehouse',
                        'branch_code' => 'APX-WH1',
                        'location' => 'Kanchipuram',
                        'address_line_1' => 'Logistics Hub, NH-44',
                        'city' => 'Kanchipuram',
                        'state' => 'Tamil Nadu',
                        'pin_code' => '602105',
                        'pt_registration_number' => 'PT-TN-602105-02',
                        'lwf_registration_number' => 'LWF-TN-602105-02',
                        'gstin' => '33AAAPA5678G1Z2',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Ram Kumar',
                        'finance_poc_email' => 'ramkumar094677@gmail.com',
                        'finance_poc_phone' => '9876543211',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'GreenPulse Renewables Ltd',
                'display_name_override' => 'GreenPulse Energy',
                'client_code' => 'GPR-003',
                'industry' => 'Renewable Energy & Utilities',
                'contract_type' => 'agency',
                'contract_start_date' => '2025-03-01',
                'contract_end_date' => '2028-02-28',
                'company_type' => 'pub_ltd',
                'country' => 'India',
                'pan_number' => 'AAACG9012H',
                'tax_id' => 'TAX-GPR-003',
                'tan_number' => 'CHEG90123H',
                'gstin' => '33AAACG9012H1Z9',
                'trust_registration_number' => null,
                'registration_number' => 'REG-GPR-2025',
                'cin_number' => 'L40100TN2025PLC090123',
                'incorporation_date' => '2018-11-10',
                'website' => 'https://greenpulse.example.com',
                'logo_path' => null,
                'accent_color' => '#16A34A',
                'payslip_template' => 'corporate_slate',
                'registered_address_line_1' => 'Green Tower, Guindy Industrial Estate',
                'registered_address_line_2' => 'Mount Road',
                'registered_city' => 'Chennai',
                'registered_state' => 'Tamil Nadu',
                'registered_pin' => '600032',
                'primary_poc_name' => 'Mohan Kumar',
                'primary_poc_email' => 'mohankumar200167@gmail.com',
                'primary_poc_phone' => '9876543212',
                'billing_model' => 'markup',
                'markup_percentage' => 12.00,
                'fixed_fee_amount' => 0.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sat,sun',
                'default_notice_period_days' => 45,
                'status' => 'active',
                'ot_billing_rule' => 'double_rate',
                'payment_net_terms' => 30,
                'credit_limit' => 750000.00,
                'late_payment_penalty_pct' => 1.50,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-GPR-2026-003',
                'po_validity_date' => '2027-03-31',
                'po_value' => 6000000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 45,
                'pt_state' => 'Tamil Nadu',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'ceiling',
                'employer_pf_wage_basis' => 'ceiling',
                'pf_applicable' => true,
                'edli_exempted' => false,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'half_yearly',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'ctc_included',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 8.33,
                'clra_license_number' => 'CLRA-TN-2025-003',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'TN/CHE/0090123/000',
                'esi_code_number' => '31000901230000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'mohankumar200167@gmail.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'premium',
                'cutoff_day' => 25,
                'payroll_lock_day' => 28,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 7,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Solar and wind infrastructure project team.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Chennai Green Tower',
                        'branch_code' => 'GPR-HQ',
                        'location' => 'Chennai',
                        'address_line_1' => 'Green Tower, Guindy Industrial Estate',
                        'city' => 'Chennai',
                        'state' => 'Tamil Nadu',
                        'pin_code' => '600032',
                        'pt_registration_number' => 'PT-TN-600032-03',
                        'lwf_registration_number' => 'LWF-TN-600032-03',
                        'gstin' => '33AAACG9012H1Z9',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Mohan Kumar',
                        'finance_poc_email' => 'mohankumar200167@gmail.com',
                        'finance_poc_phone' => '9876543212',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'Zenith Healthcare & LifeSciences',
                'display_name_override' => 'Zenith Pharma',
                'client_code' => 'ZHL-004',
                'industry' => 'Healthcare & Pharmaceuticals',
                'contract_type' => 'agency',
                'contract_start_date' => '2025-01-15',
                'contract_end_date' => '2027-12-31',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAACZ3456I',
                'tax_id' => 'TAX-ZHL-004',
                'tan_number' => 'CHEZ34567I',
                'gstin' => '33AAACZ3456I1Z4',
                'trust_registration_number' => null,
                'registration_number' => 'REG-ZHL-2025',
                'cin_number' => 'U24230TN2025PTC034567',
                'incorporation_date' => '2016-06-05',
                'website' => 'https://zenithpharma.example.com',
                'logo_path' => null,
                'accent_color' => '#DC2626',
                'payslip_template' => 'standard_blue',
                'registered_address_line_1' => 'Biotech Park, Phase II',
                'registered_address_line_2' => 'Siruseri IT Park Road',
                'registered_city' => 'Chennai',
                'registered_state' => 'Tamil Nadu',
                'registered_pin' => '603103',
                'primary_poc_name' => 'Mahalaxmi R',
                'primary_poc_email' => 'mahalaxmir97@gmail.com',
                'primary_poc_phone' => '9876543213',
                'billing_model' => 'markup',
                'markup_percentage' => 11.00,
                'fixed_fee_amount' => 0.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sat,sun',
                'default_notice_period_days' => 90,
                'status' => 'active',
                'ot_billing_rule' => 'double_rate',
                'payment_net_terms' => 30,
                'credit_limit' => 600000.00,
                'late_payment_penalty_pct' => 1.50,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-ZHL-2026-004',
                'po_validity_date' => '2027-03-31',
                'po_value' => 4500000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 90,
                'pt_state' => 'Tamil Nadu',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'ceiling',
                'employer_pf_wage_basis' => 'ceiling',
                'pf_applicable' => true,
                'edli_exempted' => false,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'annual',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => false,
                'default_gratuity_mode' => 'ctc_included',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => false,
                'bonus_rate_percentage' => 8.33,
                'clra_license_number' => 'CLRA-TN-2025-004',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'TN/CHE/0034567/000',
                'esi_code_number' => '31000345670000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'mahalaxmir97@gmail.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'enterprise',
                'cutoff_day' => 25,
                'payroll_lock_day' => 28,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 7,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Clinical research and pharma manufacturing team.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Siruseri R&D Lab',
                        'branch_code' => 'ZHL-RD',
                        'location' => 'Chennai',
                        'address_line_1' => 'Biotech Park, Phase II',
                        'city' => 'Chennai',
                        'state' => 'Tamil Nadu',
                        'pin_code' => '603103',
                        'pt_registration_number' => 'PT-TN-603103-04',
                        'lwf_registration_number' => 'LWF-TN-603103-04',
                        'gstin' => '33AAACZ3456I1Z4',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Mahalaxmi R',
                        'finance_poc_email' => 'mahalaxmir97@gmail.com',
                        'finance_poc_phone' => '9876543213',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'Quantum AI Robotics India',
                'display_name_override' => 'Quantum Robotics',
                'client_code' => 'QAI-005',
                'industry' => 'Robotics & Artificial Intelligence',
                'contract_type' => 'agency',
                'contract_start_date' => '2025-04-01',
                'contract_end_date' => '2028-03-31',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAAAC7890J',
                'tax_id' => 'TAX-QAI-005',
                'tan_number' => 'CHEQ78901J',
                'gstin' => '33AAAAC7890J1Z6',
                'trust_registration_number' => null,
                'registration_number' => 'REG-QAI-2025',
                'cin_number' => 'U73100TN2025PTC078901',
                'incorporation_date' => '2021-02-14',
                'website' => 'https://quantumai.example.com',
                'logo_path' => null,
                'accent_color' => '#7C3AED',
                'payslip_template' => 'modern_navy',
                'registered_address_line_1' => 'AI Innovation Center, OMR Road',
                'registered_address_line_2' => 'Perungudi Tech Zone',
                'registered_city' => 'Chennai',
                'registered_state' => 'Tamil Nadu',
                'registered_pin' => '600096',
                'primary_poc_name' => 'Vimal Kumar S',
                'primary_poc_email' => 'svimalkuma11@gmail.com',
                'primary_poc_phone' => '9876543214',
                'billing_model' => 'markup',
                'markup_percentage' => 15.00,
                'fixed_fee_amount' => 0.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sat,sun',
                'default_notice_period_days' => 60,
                'status' => 'active',
                'ot_billing_rule' => 'double_rate',
                'payment_net_terms' => 30,
                'credit_limit' => 1000000.00,
                'late_payment_penalty_pct' => 1.50,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-QAI-2026-005',
                'po_validity_date' => '2027-03-31',
                'po_value' => 8000000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 60,
                'pt_state' => 'Tamil Nadu',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'ceiling',
                'employer_pf_wage_basis' => 'ceiling',
                'pf_applicable' => true,
                'edli_exempted' => false,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'annual',
                'lwf_applicable' => false,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'ctc_included',
                'gratuity_applicable' => false,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 8.33,
                'clra_license_number' => 'CLRA-TN-2025-005',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'TN/CHE/0078901/000',
                'esi_code_number' => '31000789010000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'svimalkuma11@gmail.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'enterprise',
                'cutoff_day' => 25,
                'payroll_lock_day' => 28,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 7,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Next-gen robotics research and hardware assembly.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Perungudi AI Center',
                        'branch_code' => 'QAI-HQ',
                        'location' => 'Chennai',
                        'address_line_1' => 'AI Innovation Center, OMR Road',
                        'city' => 'Chennai',
                        'state' => 'Tamil Nadu',
                        'pin_code' => '600096',
                        'pt_registration_number' => 'PT-TN-600096-05',
                        'lwf_registration_number' => 'LWF-TN-600096-05',
                        'gstin' => '33AAAAC7890J1Z6',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Vimal Kumar S',
                        'finance_poc_email' => 'svimalkuma11@gmail.com',
                        'finance_poc_phone' => '9876543214',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            // ==========================================
            // GROUP B: Advanced Statutory & Fixed Fee Model (Clients 6 to 10)
            // ==========================================
            [
                'company_name' => 'BlueFin Financial Advisory Services',
                'display_name_override' => 'BlueFin Capital',
                'client_code' => 'BFA-006',
                'industry' => 'Financial Services & Investment Banking',
                'contract_type' => 'agency',
                'contract_start_date' => '2025-01-01',
                'contract_end_date' => '2027-12-31',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAACB1122K',
                'tax_id' => 'TAX-BFA-006',
                'tan_number' => 'MUMB11223K',
                'gstin' => '27AAACB1122K1Z3',
                'trust_registration_number' => null,
                'registration_number' => 'REG-BFA-2025',
                'cin_number' => 'U67120MH2025PTC112233',
                'incorporation_date' => '2015-09-12',
                'website' => 'https://bluefincapital.example.com',
                'logo_path' => null,
                'accent_color' => '#0F172A',
                'payslip_template' => 'corporate_slate',
                'registered_address_line_1' => 'Bandra-Kurla Complex (BKC)',
                'registered_address_line_2' => 'Tower 3, 14th Floor',
                'registered_city' => 'Mumbai',
                'registered_state' => 'Maharashtra',
                'registered_pin' => '400051',
                'primary_poc_name' => 'Rani S',
                'primary_poc_email' => 'rani5755765@gmail.com',
                'primary_poc_phone' => '9876543215',
                'billing_model' => 'fixed_per_candidate',
                'markup_percentage' => 0.00,
                'fixed_fee_amount' => 1500.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sat,sun',
                'default_notice_period_days' => 90,
                'status' => 'active',
                'ot_billing_rule' => 'flat_rate',
                'payment_net_terms' => 15,
                'credit_limit' => 800000.00,
                'late_payment_penalty_pct' => 2.00,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-BFA-2026-006',
                'po_validity_date' => '2027-03-31',
                'po_value' => 4000000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 90,
                'pt_state' => 'Maharashtra',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'actual_basic_da',
                'employer_pf_wage_basis' => 'actual_basic_da',
                'pf_applicable' => true,
                'edli_exempted' => true,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'half_yearly',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'over_ctc',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 20.00,
                'clra_license_number' => 'CLRA-MH-2025-006',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'MH/BAN/0011223/000',
                'esi_code_number' => '31000112230000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'rani5755765@gmail.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'enterprise',
                'cutoff_day' => 25,
                'payroll_lock_day' => 28,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 5,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Premium wealth management & financial analysts.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Mumbai BKC Office',
                        'branch_code' => 'BFA-BKC',
                        'location' => 'Mumbai',
                        'address_line_1' => 'Bandra-Kurla Complex (BKC)',
                        'city' => 'Mumbai',
                        'state' => 'Maharashtra',
                        'pin_code' => '400051',
                        'pt_registration_number' => 'PT-MH-400051-06',
                        'lwf_registration_number' => 'LWF-MH-400051-06',
                        'gstin' => '27AAACB1122K1Z3',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Rani S',
                        'finance_poc_email' => 'rani5755765@gmail.com',
                        'finance_poc_phone' => '9876543215',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'Titanium Retail & E-Commerce',
                'display_name_override' => 'Titanium Retail',
                'client_code' => 'TRE-007',
                'industry' => 'Retail & E-Commerce',
                'contract_type' => 'eor',
                'contract_start_date' => '2025-02-15',
                'contract_end_date' => '2028-02-14',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAACT3344L',
                'tax_id' => 'TAX-TRE-007',
                'tan_number' => 'BLRT33445L',
                'gstin' => '29AAACT3344L1Z1',
                'trust_registration_number' => null,
                'registration_number' => 'REG-TRE-2025',
                'cin_number' => 'U52100KA2025PTC334455',
                'incorporation_date' => '2017-03-30',
                'website' => 'https://titaniumretail.example.com',
                'logo_path' => null,
                'accent_color' => '#D97706',
                'payslip_template' => 'modern_navy',
                'registered_address_line_1' => 'Koramangala 4th Block',
                'registered_address_line_2' => '80 Feet Road',
                'registered_city' => 'Bengaluru',
                'registered_state' => 'Karnataka',
                'registered_pin' => '560034',
                'primary_poc_name' => 'Rajamani K',
                'primary_poc_email' => 'rajamani5647@gmail.com',
                'primary_poc_phone' => '9876543216',
                'billing_model' => 'fixed_per_candidate',
                'markup_percentage' => 0.00,
                'fixed_fee_amount' => 1200.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sun',
                'default_notice_period_days' => 30,
                'status' => 'active',
                'ot_billing_rule' => 'flat_rate',
                'payment_net_terms' => 15,
                'credit_limit' => 500000.00,
                'late_payment_penalty_pct' => 2.00,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-TRE-2026-007',
                'po_validity_date' => '2027-03-31',
                'po_value' => 3500000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 30,
                'pt_state' => 'Karnataka',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'actual_basic_da',
                'employer_pf_wage_basis' => 'actual_basic_da',
                'pf_applicable' => true,
                'edli_exempted' => true,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'annually',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'over_ctc',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 20.00,
                'clra_license_number' => 'CLRA-KA-2025-007',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'KA/BLR/0033445/000',
                'esi_code_number' => '31000334450000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'rajamani5647@gmail.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'premium',
                'cutoff_day' => 24,
                'payroll_lock_day' => 27,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 5,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'E-commerce fulfillment & retail store operations.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Bengaluru HQ',
                        'branch_code' => 'TRE-BLR',
                        'location' => 'Bengaluru',
                        'address_line_1' => 'Koramangala 4th Block',
                        'city' => 'Bengaluru',
                        'state' => 'Karnataka',
                        'pin_code' => '560034',
                        'pt_registration_number' => 'PT-KA-560034-07',
                        'lwf_registration_number' => 'LWF-KA-560034-07',
                        'gstin' => '29AAACT3344L1Z1',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Rajamani K',
                        'finance_poc_email' => 'rajamani5647@gmail.com',
                        'finance_poc_phone' => '9876543216',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'OmniMedia Network Pvt Ltd',
                'display_name_override' => 'OmniMedia',
                'client_code' => 'OMN-008',
                'industry' => 'Media & Broadcasting',
                'contract_type' => 'agency',
                'contract_start_date' => '2025-03-01',
                'contract_end_date' => '2028-02-28',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAACO5566M',
                'tax_id' => 'TAX-OMN-008',
                'tan_number' => 'MUMO55667M',
                'gstin' => '27AAACO5566M1Z8',
                'trust_registration_number' => null,
                'registration_number' => 'REG-OMN-2025',
                'cin_number' => 'U92100MH2025PTC556677',
                'incorporation_date' => '2014-05-18',
                'website' => 'https://omnimedia.example.com',
                'logo_path' => null,
                'accent_color' => '#E11D48',
                'payslip_template' => 'corporate_slate',
                'registered_address_line_1' => 'Film City Studio Complex',
                'registered_address_line_2' => 'Goregaon East',
                'registered_city' => 'Mumbai',
                'registered_state' => 'Maharashtra',
                'registered_pin' => '400065',
                'primary_poc_name' => 'Cloud Media Admin',
                'primary_poc_email' => 'support.cloud8@teclapayroll.com',
                'primary_poc_phone' => '9876543217',
                'billing_model' => 'fixed_per_candidate',
                'markup_percentage' => 0.00,
                'fixed_fee_amount' => 1800.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sat,sun',
                'default_notice_period_days' => 60,
                'status' => 'active',
                'ot_billing_rule' => 'flat_rate',
                'payment_net_terms' => 15,
                'credit_limit' => 650000.00,
                'late_payment_penalty_pct' => 2.00,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-OMN-2026-008',
                'po_validity_date' => '2027-03-31',
                'po_value' => 5500000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 60,
                'pt_state' => 'Maharashtra',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'actual_basic_da',
                'employer_pf_wage_basis' => 'actual_basic_da',
                'pf_applicable' => true,
                'edli_exempted' => true,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'half_yearly',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'over_ctc',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 20.00,
                'clra_license_number' => 'CLRA-MH-2025-008',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'MH/MUM/0055667/000',
                'esi_code_number' => '31000556670000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'support.cloud8@teclapayroll.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'premium',
                'cutoff_day' => 25,
                'payroll_lock_day' => 28,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 5,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Broadcasting, digital content & media production.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Mumbai Studio HQ',
                        'branch_code' => 'OMN-MUM',
                        'location' => 'Mumbai',
                        'address_line_1' => 'Film City Studio Complex',
                        'city' => 'Mumbai',
                        'state' => 'Maharashtra',
                        'pin_code' => '400065',
                        'pt_registration_number' => 'PT-MH-400065-08',
                        'lwf_registration_number' => 'LWF-MH-400065-08',
                        'gstin' => '27AAACO5566M1Z8',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Cloud Media Admin',
                        'finance_poc_email' => 'support.cloud8@teclapayroll.com',
                        'finance_poc_phone' => '9876543217',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'Stellar Infra & Builders',
                'display_name_override' => 'Stellar Infra',
                'client_code' => 'SIB-009',
                'industry' => 'Real Estate & Infrastructure',
                'contract_type' => 'eor',
                'contract_start_date' => '2025-01-01',
                'contract_end_date' => '2027-12-31',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAACS7788N',
                'tax_id' => 'TAX-SIB-009',
                'tan_number' => 'BLRS77889N',
                'gstin' => '29AAACS7788N1Z7',
                'trust_registration_number' => null,
                'registration_number' => 'REG-SIB-2025',
                'cin_number' => 'U45200KA2025PTC778899',
                'incorporation_date' => '2013-07-22',
                'website' => 'https://stellarinfra.example.com',
                'logo_path' => null,
                'accent_color' => '#B45309',
                'payslip_template' => 'standard_blue',
                'registered_address_line_1' => 'MG Road Construction Hub',
                'registered_address_line_2' => 'Trinity Circle',
                'registered_city' => 'Bengaluru',
                'registered_state' => 'Karnataka',
                'registered_pin' => '560001',
                'primary_poc_name' => 'Infra Support Admin',
                'primary_poc_email' => 'support.infra9@teclapayroll.com',
                'primary_poc_phone' => '9876543218',
                'billing_model' => 'fixed_per_candidate',
                'markup_percentage' => 0.00,
                'fixed_fee_amount' => 1400.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sun',
                'default_notice_period_days' => 30,
                'status' => 'active',
                'ot_billing_rule' => 'flat_rate',
                'payment_net_terms' => 15,
                'credit_limit' => 900000.00,
                'late_payment_penalty_pct' => 2.00,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-SIB-2026-009',
                'po_validity_date' => '2027-03-31',
                'po_value' => 7000000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 30,
                'pt_state' => 'Karnataka',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'actual_basic_da',
                'employer_pf_wage_basis' => 'actual_basic_da',
                'pf_applicable' => true,
                'edli_exempted' => true,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'annually',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'over_ctc',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 20.00,
                'clra_license_number' => 'CLRA-KA-2025-009',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'KA/BLR/0077889/000',
                'esi_code_number' => '31000778890000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'support.infra9@teclapayroll.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'standard',
                'cutoff_day' => 24,
                'payroll_lock_day' => 27,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 5,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Commercial real estate & metro civil project staff.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Bengaluru Infra Hub',
                        'branch_code' => 'SIB-BLR',
                        'location' => 'Bengaluru',
                        'address_line_1' => 'MG Road Construction Hub',
                        'city' => 'Bengaluru',
                        'state' => 'Karnataka',
                        'pin_code' => '560001',
                        'pt_registration_number' => 'PT-KA-560001-09',
                        'lwf_registration_number' => 'LWF-KA-560001-09',
                        'gstin' => '29AAACS7788N1Z7',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Infra Support Admin',
                        'finance_poc_email' => 'support.infra9@teclapayroll.com',
                        'finance_poc_phone' => '9876543218',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],

            [
                'company_name' => 'FreshHarvest Agri Processing',
                'display_name_override' => 'FreshHarvest Agri',
                'client_code' => 'FHA-010',
                'industry' => 'Agriculture & Food Processing',
                'contract_type' => 'agency',
                'contract_start_date' => '2025-04-01',
                'contract_end_date' => '2028-03-31',
                'company_type' => 'pvt_ltd',
                'country' => 'India',
                'pan_number' => 'AAACF9900P',
                'tax_id' => 'TAX-FHA-010',
                'tan_number' => 'MUMF99001P',
                'gstin' => '27AAACF9900P1Z5',
                'trust_registration_number' => null,
                'registration_number' => 'REG-FHA-2025',
                'cin_number' => 'U01100MH2025PTC990011',
                'incorporation_date' => '2019-10-01',
                'website' => 'https://freshharvest.example.com',
                'logo_path' => null,
                'accent_color' => '#15803D',
                'payslip_template' => 'modern_navy',
                'registered_address_line_1' => 'Agri Export Zone, MIDC Industrial Area',
                'registered_address_line_2' => 'Chakan Tech Park',
                'registered_city' => 'Pune',
                'registered_state' => 'Maharashtra',
                'registered_pin' => '410501',
                'primary_poc_name' => 'Food Agri Admin',
                'primary_poc_email' => 'support.food10@teclapayroll.com',
                'primary_poc_phone' => '9876543219',
                'billing_model' => 'fixed_per_candidate',
                'markup_percentage' => 0.00,
                'fixed_fee_amount' => 1600.00,
                'lop_basis_days' => 30,
                'weekly_off_pattern' => 'sun',
                'default_notice_period_days' => 30,
                'status' => 'active',
                'ot_billing_rule' => 'flat_rate',
                'payment_net_terms' => 15,
                'credit_limit' => 450000.00,
                'late_payment_penalty_pct' => 2.00,
                'invoice_cycle' => 'monthly',
                'currency' => 'INR',
                'tds_applicable_on_agency_fee' => true,
                'client_tds_percentage' => 10.00,
                'po_required' => true,
                'po_number' => 'PO-FHA-2026-010',
                'po_validity_date' => '2027-03-31',
                'po_value' => 3000000.00,
                'pref_format_pdf' => true,
                'pref_format_xlsx' => true,
                'contract_document_path' => null,
                'auto_renewal' => true,
                'notice_period_days' => 30,
                'pt_state' => 'Maharashtra',
                'state_registration_option' => 'single_state',
                'pf_ceiling' => 15000.00,
                'employee_pf_wage_basis' => 'actual_basic_da',
                'employer_pf_wage_basis' => 'actual_basic_da',
                'pf_applicable' => true,
                'edli_exempted' => true,
                'health_insurance_enabled' => true,
                'esi_limit' => 21000.00,
                'esi_applicable' => true,
                'lwf_frequency' => 'half_yearly',
                'lwf_applicable' => true,
                'tds_regime' => 'new',
                'tds_applicable' => true,
                'default_gratuity_mode' => 'over_ctc',
                'gratuity_applicable' => true,
                'statutory_bonus_applicable' => true,
                'bonus_rate_percentage' => 20.00,
                'clra_license_number' => 'CLRA-MH-2025-010',
                'clra_license_expiry' => '2027-12-31',
                'pf_establishment_code' => 'MH/PUN/0099001/000',
                'esi_code_number' => '31000990010000101',
                'client_portal_enabled' => true,
                'portal_primary_email' => 'support.food10@teclapayroll.com',
                'portal_access_level' => 'full',
                'portal_users_limit' => 5,
                'portal_view_salary' => true,
                'portal_view_invoices' => true,
                'portal_view_payslips' => true,
                'portal_raise_requests' => true,
                'portal_require_2fa' => false,
                'portal_session_timeout' => 30,
                'portal_ip_whitelist' => null,
                'sla_tier' => 'premium',
                'cutoff_day' => 24,
                'payroll_lock_day' => 27,
                'salary_credit_day' => '1',
                'invoice_dispute_window_days' => 5,
                'invoice_raise_day' => 1,
                'payroll_convention' => 'calendar_month',
                'custom_cycle_start_day' => 1,
                'custom_cycle_end_day' => 30,
                'auto_reminders' => true,
                'client_notes' => 'Agri-processing plants & cold storage team.',
                'account_manager_id' => $adminId,
                'backup_account_manager_id' => $adminId,

                'branches' => [
                    [
                        'branch_name' => 'Pune Processing Plant',
                        'branch_code' => 'FHA-PUN',
                        'location' => 'Pune',
                        'address_line_1' => 'Agri Export Zone, MIDC Industrial Area',
                        'city' => 'Pune',
                        'state' => 'Maharashtra',
                        'pin_code' => '410501',
                        'pt_registration_number' => 'PT-MH-410501-10',
                        'lwf_registration_number' => 'LWF-MH-410501-10',
                        'gstin' => '27AAACF9900P1Z5',
                        'gst_registration_type' => 'regular',
                        'finance_poc_name' => 'Food Agri Admin',
                        'finance_poc_email' => 'support.food10@teclapayroll.com',
                        'finance_poc_phone' => '9876543219',
                        'is_head_office' => true,
                        'is_primary_billing_branch' => true,
                    ]
                ]
            ],
        ];

        Schema::disableForeignKeyConstraints();

        DB::table('client_contacts')->truncate();
        DB::table('client_branches')->truncate();
        DB::table('clients')->truncate();

        foreach ($clientsData as $data) {
            $branches = $data['branches'];
            unset($data['branches']);

            $client = Client::create($data);

            // Create Branches
            foreach ($branches as $branchData) {
                $branchData['client_id'] = $client->id;
                ClientBranch::create($branchData);
            }

            // Create Contacts
            // 1. Primary POC
            ClientContact::create([
                'client_id' => $client->id,
                'contact_type' => 'primary',
                'full_name' => $client->primary_poc_name,
                'designation' => 'Managing Director',
                'email' => $client->primary_poc_email,
                'phone' => $client->primary_poc_phone,
                'is_primary_contact' => true,
                'is_whatsapp_same' => true,
                'cc_on_invoice' => true,
                'receive_onboarding_kits' => true,
                'preference_email' => true,
                'preference_sms' => true,
                'preference_whatsapp' => true,
            ]);

            // 2. Finance POC
            ClientContact::create([
                'client_id' => $client->id,
                'contact_type' => 'finance',
                'full_name' => $client->primary_poc_name . ' (Finance)',
                'designation' => 'Finance Controller',
                'email' => $client->primary_poc_email,
                'phone' => $client->primary_poc_phone,
                'is_primary_contact' => false,
                'is_whatsapp_same' => true,
                'cc_on_invoice' => true,
                'receive_onboarding_kits' => false,
                'preference_email' => true,
                'preference_sms' => true,
                'preference_whatsapp' => true,
            ]);

            // 3. HR POC
            ClientContact::create([
                'client_id' => $client->id,
                'contact_type' => 'hr',
                'full_name' => $client->primary_poc_name . ' (HR)',
                'designation' => 'HR Director',
                'email' => $client->primary_poc_email,
                'phone' => $client->primary_poc_phone,
                'is_primary_contact' => false,
                'is_whatsapp_same' => true,
                'cc_on_invoice' => false,
                'receive_onboarding_kits' => true,
                'preference_email' => true,
                'preference_sms' => true,
                'preference_whatsapp' => true,
            ]);

            // Create Client Portal User if email doesn't exist
            if ($client->portal_primary_email) {
                User::updateOrCreate(
                    ['email' => $client->portal_primary_email],
                    [
                        'name' => $client->primary_poc_name,
                        'password' => Hash::make('Password@123'),
                        'role' => 'client',
                        'client_id' => $client->id,
                        'status' => 'active',
                    ]
                );
            }
        }

        Schema::enableForeignKeyConstraints();

        $this->command->info('TenClientsSeeder completed successfully! 10 complete clients seeded with 100% database fields.');
    }
}
