import { Download, Trash2 } from 'lucide-react';
import Card from '../../../../Components/ui/Card';
import Badge from '../../../../Components/ui/Badge';
import EmptyState from '../../../../Components/ui/EmptyState';
import { FileText } from 'lucide-react';

export default function HistoryTable({ history, onDownload, onDelete }) {
  return (
    <Card title="Report History" subtitle="Previously generated Form B reports.">
      {(!history || history.length === 0) ? (
        <EmptyState icon={FileText} title="No Form B reports yet" message="Reports you generate will appear here." />
      ) : (
        <div className="table-responsive">
          <table className="data-table">
            <thead>
              <tr>
                <th>Month & Year</th>
                <th>Generated On</th>
                <th>Payroll Run</th>
                <th>Status</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {history.map((row) => (
                <tr key={row.id}>
                  <td>{row.month_year}{row.branch_name && row.branch_name !== 'All Branches' ? ` · ${row.branch_name}` : ''}</td>
                  <td>{row.generated_on || '—'}</td>
                  <td>{row.payroll_run_label}</td>
                  <td><Badge status={row.status} /></td>
                  <td>{row.generated_by}</td>
                  <td>
                    <div style={{ display: 'flex', gap: '0.4rem' }}>
                      <button className="btn btn-xs btn-outline" title="Download PDF" onClick={() => onDownload(row.id, 'pdf')}>
                        <Download size={13} />
                      </button>
                      <button className="btn btn-xs btn-outline" title="Delete" onClick={() => onDelete(row.id)} style={{ color: 'var(--status-danger)' }}>
                        <Trash2 size={13} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Card>
  );
}
