// Client Statutory Defaults — ported from payroll-new/assets/script.js L452-L543

export const CLIENT_STATUTORY_DEFAULTS = {
  mahindra: {
    name: 'Mahindra Corp',
    contractType: 'agency_payroll',
    pfApplicable: true,
    pfCeiling: 15000,
    esiApplicable: true,
    esiLimit: 21000,
    esiContributionPeriodEnd: '2026-09-30',
    ptApplicable: true,
    ptBasis: 'auto',
    lwfApplicable: true,
    lwfFrequency: 'annual',
    tdsRegime: 'new',
    gratuityMode: 'part_of_ctc',
    statutoryBonusApplicable: true,
    bonusRate: 8.33,
    lopBasis: '26_days',
  },
  tcs: {
    name: 'Tata Consultancy Services — EOR',
    contractType: 'eor',
    pfApplicable: true,
    pfCeiling: 15000,
    esiApplicable: false,
    esiLimit: 21000,
    esiContributionPeriodEnd: '2026-09-30',
    ptApplicable: true,
    ptBasis: 'auto',
    lwfApplicable: false,
    lwfFrequency: 'annual',
    tdsRegime: 'old',
    gratuityMode: 'over_and_above',
    statutoryBonusApplicable: false,
    bonusRate: 8.33,
    lopBasis: '30_days',
  },
  tcs_agency: {
    name: 'Tata Consultancy Services — Agency',
    contractType: 'agency_payroll',
    pfApplicable: true,
    pfCeiling: 15000,
    esiApplicable: true,
    esiLimit: 21000,
    esiContributionPeriodEnd: '2026-09-30',
    ptApplicable: true,
    ptBasis: 'auto',
    lwfApplicable: true,
    lwfFrequency: 'annual',
    tdsRegime: 'old',
    gratuityMode: 'part_of_ctc',
    statutoryBonusApplicable: true,
    bonusRate: 8.33,
    lopBasis: '30_days',
  },
  reliance: {
    name: 'Reliance Digital',
    contractType: 'agency',
    pfApplicable: true,
    pfCeiling: 15000,
    esiApplicable: true,
    esiLimit: 25000,
    esiContributionPeriodEnd: '2026-09-30',
    ptApplicable: false,
    ptBasis: 'auto',
    lwfApplicable: true,
    lwfFrequency: 'monthly',
    tdsRegime: 'new',
    gratuityMode: 'part_of_ctc',
    statutoryBonusApplicable: true,
    bonusRate: 10.0,
    lopBasis: 'inherit_global',
  },
  wipro: {
    name: 'Wipro Ltd',
    contractType: 'agency',
    pfApplicable: true,
    pfCeiling: 15000,
    esiApplicable: true,
    esiLimit: 21000,
    esiContributionPeriodEnd: '2026-09-30',
    ptApplicable: true,
    ptBasis: 'auto',
    lwfApplicable: true,
    lwfFrequency: 'bi-annual',
    tdsRegime: 'employee_choice',
    gratuityMode: 'over_and_above',
    statutoryBonusApplicable: true,
    bonusRate: 8.33,
    lopBasis: '30_days',
  },
};
